[c]
calc=["calculate"]
char=["character"]
chg=["change"]
chk=["check"]
clr=["clear","color"]
clk=["click","clock"]
cli=["command line interface","client"]
cont=["content"]
ctx=["context"]
comm=["common","communication"]
conf=["config"]
col=["column"]
cmd=["command"]
cmp=["compare"]
cpl=["complete"]
conn=["connection"]
cons=["construct"]
csmer=["consumer"]
ctrl=["control"]
conv=["convert"]
coord=["coordinates"]
cp=["copy"]
cnt=["count"]
cter=["counter"]
cur=["current"]
csr=["cursor"]
cyl=["cylinder"]