[d]
db=["database"]
dep=["dependency"]
dbg=["debug"]
deco=["decode"]
decre=["decrease"]
def=["default"]
deg=["degree"]
dly=["delay"]
del=["delete"]
desc=["descriptor"]
dese=["deserialize"]
dst=["destination"]
dev=["device"]
dict=["dictionary"]
diff=["different"]
dig=["digit"]
dim=["dimension"]
dirt=["direct"]
dir=["directory"]
dis=["disable"]
disp=["display"]
div=["divide"]
dlg=["dialog"]
doc=["document"]
dbl=["double"]
drv=["driver"]
dup=["duplicate"]
dyn=["dynamic"]