[i]
inc=["increment"]
ineff=["ineffective"]
info=["infomation"]
id=["identifier"]
idx=["index"]
in=["input"]
img=["image"]
imp=["implement"]
incre=["increase"]
init=["initialization"]
isrt=["insert"]
ins=["instance"]
istr=["instruction"]
intr=["interrupt"]
intv=["interval"]
inv=["invalid"]
invt=["invert"]