[p]
pkg=["package"]
pass=["password"]
param=["parameter"]
perf=["performance"]
perd=["period"]
permut=["permutation"]
perm=["permit","permission"]
pic=["picture"]
pt=["point"]
pos=["position"]
posi=["positive"]
pwr=["power"]
prev=["previous"]
pre=["prefix"]
prt=["print"]
prio=["priority"]
proc=["process"]
prod=["product"]
pf=["profile"]
proj=["project"]
prog=["program"]
prop=["property"]
proto=["protocol"]
prot=["protect"]
prx=["proxy"]
pub=["public"]