[r]
r=["read"]
rdy=["ready"]
react=["reactive"]
rcl=["recall"]
rece=["receive"]
rect=["rectangle"]
recu=["recursion"]
ref=["reference"]
reg=["register"]
rgn=["region"]
rel=["release"]
rpt=["repeat"]
repo=["repository"]
req=["request"]
resv=["reserve"]
rst=["reset"]
res=["resource"]
rsp=["response"]
rslt=["result"]
resu=["resume"]
ret=["return"]
revs=["reverse"]